### ISSUE TITLE
Failure when importing *.ibw file in Pyjibe user interface

### ISSUE THREAD

**Issue by tenoriomaria** [AFM-analysis/afmformats#8]
I am very new at programming with Python.
When starting the Pyjibe program (I have created an environment with Python 3.6) and trying to load single files with extensions *.ibw  this problem appears:

_Unhandled exception in PyJibe version 0.7.3:
Traceback (most recent call last):
  File "/Users/maria/opt/anaconda3/envs/python36/lib/python3.6/site-packages/pyjibe/head/main.py", line 151, in on_open_single
    self.load_data(files=n, retry_open=self.on_open_single)
  File "/Users/maria/opt/anaconda3/envs/python36/lib/python3.6/site-packages/pyjibe/head/main.py", line 210, in load_data
    self.add_subwindow(aclass, flist)
  File "/Users/maria/opt/anaconda3/envs/python36/lib/python3.6/site-packages/pyjibe/head/main.py", line 70, in add_subwindow
    inst.add_files(flist)
  File "/Users/maria/opt/anaconda3/envs/python36/lib/python3.6/site-packages/pyjibe/fd/main.py", line 147, in add_files
    grp = nanite.IndentationGroup(f, callback=callback)
  File "/Users/maria/opt/anaconda3/envs/python36/lib/python3.6/site-packages/nanite/group.py", line 48, in __init__
    self += load_group(path, callback=callback)
  File "/Users/maria/opt/anaconda3/envs/python36/lib/python3.6/site-packages/nanite/group.py", line 23, in load_group
    data = load_data(path, callback=callback)
  File "/Users/maria/opt/anaconda3/envs/python36/lib/python3.6/site-packages/nanite/read.py", line 55, in load_data
    measurements = afmformats.load_data(pp, callback=callback)
  File "/Users/maria/opt/anaconda3/envs/python36/lib/python3.6/site-packages/afmformats/formats.py", line 117, in load_data
    meta_override=meta_override):
  File "/Users/maria/opt/anaconda3/envs/python36/lib/python3.6/site-packages/afmformats/fmt_igor.py", line 55, in load_igor
    time, ap = notes["Time"].split()
ValueError: not enough values to unpack (expected 2, got 1)

I think it is related with setup.py, because when I write in the terminal 'python3 setup.py test'. it replies with 'no such file or directory'

I attach an example of any of my *.ibw files
[SiN_FD_plot.ibw.zip](https://github.com/AFM-analysis/PyJibe/files/4415818/SiN_FD_plot.ibw.zip)

**Comment by paulmueller** [comment]
Thanks for the issue. This is actually just a parsing problem in afmformats. I transferred it here because of that.

**Comment by paulmueller** [comment]
If you installed PyJibe via a virtual environment, you can simply upgrade afmformats via
`pip install afmformats==0.10.1` and it should work.

**Comment by tenoriomaria** [comment]
?Now it works, thank you so much!

________________________________
